on: push
name: Build/Deploy on push
jobs:
  web-deploy:
    name: 🔨 Build & 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📦 Setup Node 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 🔨 Build Project
      id: build
      env:
        VITE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        VITE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        VITE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        VITE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        VITE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        VITE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        VITE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      run: |
        npm ci
        npm run build

    - name: ✅ Build successful
      if: steps.build.outcome == 'success'
      run: echo "Build successful"

    - name: 🚀 Deploy to FTP server
      id: ftp-deploy
      if: github.ref == 'refs/heads/main'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_URL }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        server-dir: www/
    
    - name: ✅ Deployment successful
      if: steps.ftp-deploy.outcome == 'success'
      run: echo "Successfully deployed to https://www.antoine-podvin.fr"
